### ISSUE TITLE
fix example on webserver

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#15]
-	“on the website, the name of the genes in the example should be given.”
Replace the gene names in the example this way (note that there are few entries that have the same gene name – it’s on purpose! It means that there are a few exons of the same gene):
current	New
AT1G56045	Gene_sample1
AT2G40205	Gene_sample2
AT3G08520	Gene_sample3
AT3G11120	Gene_sample4
AT3G56020	Gene_sample5

**Comment by shlomtzion** [comment]
done
