### ISSUE TITLE
repair results csv for download

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#17]
-	The results csv for download looks terrible… Please make it look exactly like the one in the html.

**Comment by shiranab** [comment]
ask from Shlomtzion the code that parses gal's pickle result. make Pandas df from it and convert it to html exactly how Shlomtzion made it. Then it could be easily downloadable from the html and easy to sort.

**Comment by shlomtzion** [comment]
I tried to convert with this tool: https://conversiontools.io/conversion/convert_html_table_to_csv
It didn't well: 
![image](https://user-images.githubusercontent.com/16325993/34466590-9edb7592-eee1-11e7-8cf4-c527dd447722.png)


I think we should print it ourselves into a CSV file

**Comment by shlomtzion** [comment]
There is a bug when there are two target sites for one gene.
See here:
![image](https://user-images.githubusercontent.com/16325993/35264381-3e7d6c00-0025-11e8-96a2-b54674340dd2.png)

**Comment by HyamsG** [comment]
thanks, on it
