### ISSUE TITLE
Sort output table by #mismatches (after the previous sortings)

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#18]
-	The tables should be sorted by score and then by number of mismatches. 
Example: 
o	the third sgRNA is better than the first even though the sgRNA scores are similar (they are both 4.0). 
o	within the gene targets: look at the third sgRNA (the two marked targets). The top one has two mismatches and the bottom has none, so it should appear before.

**Comment by HyamsG** [comment]
A few questions:
1) this is relevant only when the scores are equal?
2) sorted by the total number of mm? how to consider mm when there is more than one target for a gene?

**Comment by shiranab** [comment]
1. yes
2. the one with least mms within a gene should be first

The explanation above refers to these examples: (the image was not loaded before)
![image](https://user-images.githubusercontent.com/8642463/34421705-8208923a-ec19-11e7-9f35-818b7791dafe.png)

**Comment by HyamsG** [comment]
done - the new version of the code, on which I'm adding the changes, available on /groups/itay_mayrose/galhyams/CRISPys_revision_25_12
