### ISSUE TITLE
change the blue color in the header of the website

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#21]
The color of the column and the box it's in do not match. Please change the blue color to code: #4F81BD.

Thanks!

**Comment by shlomtzion** [comment]
Done

**Comment by shiranab** [comment]
Nice, thanks!

2018-01-08 11:00 GMT+02:00 shlomtzion <notifications@github.com>:

**Comment by shlomtzion** [comment]
Thank you!
