### ISSUE TITLE
Run for 10 threshold

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#4]
Run for 10 threshold (fixed intervals or quantiles), and compare to MT (Shiran prepares MT outputs for analysis)

For comparison between CFD and CRISTA, we should include two additional thresholds that correspond to the 50th and 90th quantiles

**Comment by HyamsG** [comment]
done for the CFD funct, for 20 thrs. Will add a link, How to present the results?

**Comment by shiranab** [comment]
send me the summary, I'll think about it

**Comment by HyamsG** [comment]
/groups/itay_mayrose/galhyams/CRISPIS_V_1.2_Data/revision_analsys/CFD_versatile_thr

**Comment by shiranab** [comment]
These are the thresholds corresponding to the quantiles:
5 0.16
10 0.22
15 0.25
20 0.27
25 0.29
30 0.32
35 0.34
40 0.37
45 0.40
50 0.43
55 0.45
60 0.48
65 0.51
70 0.55
75 0.57
80 0.60
85 0.63
90 0.66
95 0.73

**Comment by shiranab** [comment]
quantile threshold
5 0.16
10 0.22
15 0.25
20 0.27
25 0.29
30 0.32
35 0.34
40 0.37
45 0.40
50 0.43
55 0.45
60 0.48
65 0.51
70 0.55
75 0.57
80 0.60
85 0.63
90 0.66
95 0.73

**Comment by shiranab** [comment]
Done, for 0.05 jumps thresholds between 0,1
![thresholds_sexp-somega_fullcoverage](https://user-images.githubusercontent.com/8642463/34725136-ae3b3c0c-f558-11e7-9523-115e35cec615.png)
![thresholds_multitargeter_fullcoverage](https://user-images.githubusercontent.com/8642463/34725137-ae5ce2e4-f558-11e7-940d-d5ccbaceebd0.png)
![thresholds_sexp-somega](https://user-images.githubusercontent.com/8642463/34725139-ae7d7cca-f558-11e7-88c8-f5153f392b92.png)

**Comment by HyamsG** [comment]
Hi,
very nice graphs! would like to see how to make those! :)

It is very problematic to call the output as 'number of successful runs'.
It is better to describe it exactly as it is: number of whole-family
cleavages, for example.

**Comment by shiranab** [comment]
Changed. Thanks.

I added the figures and explanations to the results
