### ISSUE TITLE
bug: two identical targets in the same gene are not presented in output

### ISSUE THREAD

**Issue by shiranab** [MayroseLab/CRISPys#7]
See family: HOM03D012967, designed sgRNA: TTCTCGGATGCCTTAGTTGA. There are two identical targets (TTCTCGGATGCCTTAGTTGA) in gene SL07G009550, but only one in the html output. There should be two entries. Their positions in the genes should appear in the table as well.

**Comment by HyamsG** [comment]
Adding the positions of the genes to the online table - I just wrote the code finding the pos (in file name "WrapperVers3.py, for now", but I'll wait with the changes in the tables until we'll accurately decide on - as a lesson from previous modification in the table that eventually were not unanimously accepted.

**Comment by shiranab** [comment]
Can be closed?

**Comment by shiranab** [comment]
@HyamsG ?
